name: word_guesser
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  cloud_firestore: ^3.4.5
  cloud_firestore_odm: ^1.0.0-dev.27
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.6.4
  firebase_core: ^1.21.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  freezed_annotation: ^2.1.0
  get_it: ^7.2.0
  hooks_riverpod: ^1.0.4
  injectable: ^1.5.3
  json_annotation: ^4.6.0
  riverpod: ^1.0.3

dev_dependencies:
  build_runner: ^2.2.0
  cloud_firestore_odm_generator: ^1.0.0-dev.27
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  injectable_generator: ^1.5.4
  json_serializable: ^6.3.1
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true
