name: word_guesser
description: Learn a new language one image at a time

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  audioplayers: ^1.0.1
  cached_network_image: ^3.2.1
  cloud_firestore: ^3.4.5
  cloud_firestore_odm: ^1.0.0-dev.27
  confetti: ^0.7.0
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  firebase_auth: ^3.6.4
  firebase_core: ^1.21.0
  flex_color_scheme: ^5.1.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  flutter_tts: ^3.2.2
  freezed_annotation: ^2.1.0
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  hooks_riverpod: ^1.0.4
  injectable: ^1.5.3
  json_annotation: ^4.6.0
  riverpod: ^1.0.3

dev_dependencies:
  build_runner: ^2.2.0
  change_app_package_name: ^1.1.0
  cloud_firestore_odm_generator: ^1.0.0-dev.27
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  injectable_generator: ^1.5.4
  json_serializable: ^6.3.1
  very_good_analysis: ^3.0.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/launch_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "path/to/image.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "path/to/image.png"
    icon_size: 48 # min:48, max:256, default: 48

flutter:
  uses-material-design: true

  assets:
    - assets/sounds/
    - assets/images/
